package resolver_user

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	graph_model "hshelby-tkcled-product/src/graph/generated/model"
	generated_user "hshelby-tkcled-product/src/graph/generated/user"
)

// Parent is the resolver for the parent field.
func (r *categoryResolver) Parent(ctx context.Context, obj *graph_model.Category) (*graph_model.Category, error) {
	panic(fmt.Errorf("not implemented: Parent - parent"))
}

// Children is the resolver for the children field.
func (r *categoryResolver) Children(ctx context.Context, obj *graph_model.Category) ([]graph_model.Category, error) {
	panic(fmt.Errorf("not implemented: Children - children"))
}

// Category returns generated_user.CategoryResolver implementation.
func (r *Resolver) Category() generated_user.CategoryResolver { return &categoryResolver{r} }

type categoryResolver struct{ *Resolver }
