package resolver_user

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	graph_model "hshelby-tkcled-product/src/graph/generated/model"
)

// ProductDetail is the resolver for the productDetail field.
func (r *queryResolver) ProductDetail(ctx context.Context, productID string) (*graph_model.Product, error) {
	panic(fmt.Errorf("not implemented: ProductDetail - productDetail"))
}

// ProductPagination is the resolver for the productPagination field.
func (r *queryResolver) ProductPagination(ctx context.Context, page int, limit int, orderBy *string, search map[string]interface{}) (*graph_model.ProductPagination, error) {
	panic(fmt.Errorf("not implemented: ProductPagination - productPagination"))
}

// Query returns generated_user.QueryResolver implementation.

type queryResolver struct{ *Resolver }
