package resolver_user

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49-dev

import (
	"context"
	"fmt"
	graph_model "hshelby-tkcled-product/src/graph/generated/model"
	generated_user "hshelby-tkcled-product/src/graph/generated/user"
)

// Category is the resolver for the category field.
func (r *productResolver) Category(ctx context.Context, obj *graph_model.Product) (*graph_model.Category, error) {
	panic(fmt.Errorf("not implemented: Category - category"))
}

// Product returns generated_user.ProductResolver implementation.
func (r *Resolver) Product() generated_user.ProductResolver { return &productResolver{r} }

type productResolver struct{ *Resolver }

