package resolver_user

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.48

import (
	"context"
	"fmt"
	graph_model "hshelby-tkcled-product/src/graph/generated/model"
	generated_user "hshelby-tkcled-product/src/graph/generated/user"
)

// Category is the resolver for the category field.
func (r *productResolver) Category(ctx context.Context, obj *graph_model.Product) (*graph_model.Category, error) {
	panic(fmt.Errorf("not implemented: Category - category"))
}

// Product returns generated_user.ProductResolver implementation.
func (r *Resolver) Product() generated_user.ProductResolver { return &productResolver{r} }

type productResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *productResolver) CategoryID(ctx context.Context, obj *graph_model.Product) (*graph_model.Category, error) {
	panic(fmt.Errorf("not implemented: CategoryID - category_id"))
}
